// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn15CGy88sc4XG0tu33LMHEFlbVGcxKLQ',
    appId: '1:435263506195:web:4b4888d8dd8745fc337ce6',
    messagingSenderId: '435263506195',
    projectId: 'projek-akhir-waspas-mobprog',
    authDomain: 'projek-akhir-waspas-mobprog.firebaseapp.com',
    storageBucket: 'projek-akhir-waspas-mobprog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE1Hvi4uJAotoPz8UTDg8HpfGox1N7bsI',
    appId: '1:435263506195:android:3809f8f5d3639cd4337ce6',
    messagingSenderId: '435263506195',
    projectId: 'projek-akhir-waspas-mobprog',
    storageBucket: 'projek-akhir-waspas-mobprog.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn15CGy88sc4XG0tu33LMHEFlbVGcxKLQ',
    appId: '1:435263506195:web:2fb84e089bbf600e337ce6',
    messagingSenderId: '435263506195',
    projectId: 'projek-akhir-waspas-mobprog',
    authDomain: 'projek-akhir-waspas-mobprog.firebaseapp.com',
    storageBucket: 'projek-akhir-waspas-mobprog.firebasestorage.app',
  );
}
